### ISSUE TITLE
Migrate the install.sh script to work with setup.py

### ISSUE THREAD

**Issue by schae234** [LinkageIO/Camoco#67]
Currently, we use an bash script to install camoco. This is not cross compatible with other systems (especially ones that do not use bash). We want to be able to clone the camoco repo and handle the dependencies using just setup.py.

We can do this by injecting some `pip install commands` 

```
from setuptools.command.develop import develop
from setuptools.command.install import install 

  [ ... ]

class PostDevelopCommand(develop):
    """Post-installation for development mode."""
    def run(self):
        print('Running post-installation setup')
        check_call('''\
	    pip install -r requirements.txt
        '''.split())
        develop.run(self)

class PostInstallCommand(install):
    """Post-installation for installation mode."""
    def run(self): 
        print('Running post-installation setup')
        check_call('''\
            pip install -r requirements.txt
        '''.split())
install.run(self)

 [ ... ]

setup(
 [ ... ]
    cmdclass = {
        'build_ext' : build_ext,
        'develop': PostDevelopCommand,
        'install': PostInstallCommand,
    },
 [ ... ]
)
```
Then we should be able to make a virtualenv and install
```
$ git clone git@github.com:schae234/Camoco.git
$ cd Camoco
$ conda create -n  camoco python=3
$ source activate camoco
# Install some dependencies
$ conda install Cython numpy
# Run the setup.py script
$ python setup.py install
```

This should be **much** more cross compatible than what camoco is currently doing.

**Comment by seraco** [comment]
Can I work on that?

**Comment by schae234** [comment]
@seraco That would be great! If you have any questions or need any clarifications, let me know!

**Comment by seraco** [comment]
Now I have no time to work on this 😞. I will have to leave it to somebody else by now.

**Comment by schae234** [comment]
Hey, @seraco, thank you for all your other work! Let us know if you have more time later, we'd love more community input!

**Comment by schae234** [comment]
This is related to #69 and is now resolved! Nice work everyone!
