### ISSUE TITLE
Additional Roadmap Tasks

### ISSUE THREAD

**Issue by schae234** [LinkageIO/Camoco#77]
Hi @annakrystalli  and @acabunoc 👋 

Here is a recap from our brainstorming session 💭 :

### Additional Roadmapping tasks 🚗  ( adding to #63 )
- [x] Start thinking about establishing a **very clear** release cycle and include DOIs.

This process should be dead simple for people who stumble upon the project. They should know where to get stable versions of Camoco and how to cite it in their work, i.e., "We used camoco (DOI:xxxx) to do our network analysis". Right now the installation instructions are for GitHub. I will update this so that people who follow the installation instructions are either getting it from a repository (i.e. conda) or from from the latest stable release version here.

- [x] Add a demo or "vignette" to the GitHub page

If github is going to be the landing page for the project, people should immediately see it in action. To do this, I'll add some small data-sets to include with Camoco as well as some demos to showcase what is possible with Camoco. It would also be worthwhile to look into the python equivalent of notebooks and see if those would be compatible with GitHub for a sort of interactive experience.

**Comment by annakrystalli** [comment]
So good to catch up! And really looking forward to try and play with some dummy data :)

**Comment by schae234** [comment]
This is done and available here: https://goo.gl/TN1L1K

Still need to migrate the gifs to docs, but they are there.
