### ISSUE TITLE
ImportError: cannot import name Timestamp

### ISSUE THREAD

**Issue by hriday535** [LinkageIO/Camoco#90]
Please help me resolve this issue, i am getting it when trying to run below text file code on jupyter as : %run nameoftextfile.py

import numpy as np
import pandas as pd
from ggplot import *
import Timestamp

def main():
    #df_brands=pd.read_csv("brand_detailsone.csv")
    df_brands=pd.read_csv("Salesstore.csv")
    print df_brands.astype
    print df_brands.head()
    print df_brands.shape
    
      
    
if __name__=='__main__':
     main()

**Comment by schae234** [comment]
Hi @hriday535 

It looks like you don't have the package "Timestamp" installed. Do you know if it is available from the python package index? Can you install it via `pip install Timestamp`?
